- CHANGELOG.md
- README.md
- lib/qonfig/command_set.rb
- lib/qonfig/data_set.rb
- lib/qonfig/settings.rb
- spec/features/config_definition_spec.rb
API:
```ruby
config = Config.new do |conf|
config.a.b.c = 1
config.d = '2'
end
```
> Instant configuration

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- spec/features/config_reloading.rb
Added an ability to reload config instance after config class changes. See README.md for details.
> Config instance reloading

- CHANGELOG.md
- README.md
- lib/qonfig.rb
- lib/qonfig/commands/load_from_self.rb
- lib/qonfig/commands/load_from_yaml.rb
- lib/qonfig/loaders/yaml.rb
- spec/features/load_from_self/with_erb_instructions_spec.rb
- spec/features/load_from_self/with_hash_like_data_representation_spec.rb
- spec/features/load_from_yaml_spec.rb
- spec/fixtures/shared_settings.yml
- spec/fixtures/shared_settings_with_aliases.yml
- spec/fixtures/with_erb_instructions.yml
- load_from_yaml
- load_from_self
> Support for ERB instructions in YAML

- .rubocop.yml
- CHANGELOG.md
- README.md
- lib/qonfig.rb
- lib/qonfig/command_set.rb
- lib/qonfig/commands/load_from_self.rb
- lib/qonfig/data_set.rb
- lib/qonfig/error.rb
- lib/qonfig/settings.rb
- lib/qonfig/settings/lock.rb
- qonfig.gemspec
- spec/features/load_from_self/with_hash_like_data_representation_spec.rb
> Thread-safe implementation

- CHANGELOG.md
- README.md
- lib/qonfig.rb
- lib/qonfig/configurable.rb
- lib/qonfig/dsl.rb
- spec/features/mixin_spec.rb
**API**:
- Class-level:
- `.configuration` - settings definitions;
- `.configure` - configuration;
- `.config` - config object;
- Instance-level:
- `#configure` - configuration;
- `#config` - config object;
---
**Features**:
- all Qonfig-related features;
- different class-level and instance-level config objects;
- working inheritance :)
---
> [Qonfig::Configurable] Provide configurable behaviour to any class or module and their instances

- .rubocop.yml
- CHANGELOG.md
- README.md
- lib/qonfig/command_set.rb
- lib/qonfig/commands/compose.rb
- lib/qonfig/commands/load_from_env.rb
- lib/qonfig/commands/load_from_self.rb
- lib/qonfig/commands/load_from_yaml.rb
- lib/qonfig/data_set.rb
- lib/qonfig/dsl.rb
- lib/qonfig/error.rb
- lib/qonfig/loaders/yaml.rb
- lib/qonfig/settings.rb
- lib/qonfig/version.rb
- spec/features/config_definition_spec.rb
- spec/features/core_methods_redefenition_spec.rb
- spec/features/dig_functionality_spec.rb
- spec/features/indifferent_access_spec.rb
- spec/features/load_from_env_spec.rb
- spec/features/load_from_self/with_non_hash_like_data_representation_spec.rb
- spec/features/load_from_yaml_spec.rb
- spec/features/settings_as_predicates_spec.rb
See CHANGELOG.md and README.md
> [Release] 0.1.0 => 0.2.0

- qonfig.gemspec
Support for Ruby 2.2 has ended
> [gemspec] required ruby version: >=2.2.10 => >=2.3.7

- qonfig.gemspec
- armitage-rubocop (0.3.0 => 0.4.0)
> Updated dependencies

- CHANGELOG.md
- README.md
- lib/qonfig.rb
- lib/qonfig/commands/load_from_json.rb
- lib/qonfig/dsl.rb
- lib/qonfig/error.rb
- lib/qonfig/loaders/basic.rb
- lib/qonfig/loaders/json.rb
- spec/features/load_from_json_spec.rb
- spec/features/load_from_yaml_spec.rb
- spec/fixtures/json_array_sample.json
- spec/fixtures/json_object_sample.json
Load config definitions from `*.json` file. Works in `load_from_yaml` manner.
---
> [commands] load_from_json

- CHANGELOG.md
- lib/qonfig/version.rb
- see CHANGELOG.md
- see qonfig.gemspec
> [release] v0.4.0 => v0.5.0

- .travis.yml
- CHANGELOG.md
- README.md
- lib/qonfig/configurable.rb
- spec/features/mixin_spec.rb
> [mixin/#shared_config] access to the class level config object

- .travis.yml
- CHANGELOG.md
- README.md
- lib/qonfig/configurable.rb
- lib/qonfig/version.rb
- qonfig.gemspec
- spec/features/mixin_spec.rb
> [RELEASE] 0.5.0 => 0.6.0

- .rubocop.yml
- qonfig.gemspec
- gem specification: minimal ruby version 2.3.8
- code style: target 2.5.3
- armitage-rubocop: actualized (0.11 => 0.12)
> [gem] Actualized dependencies

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/settings.rb
- spec/features/slice_functionality_spec.rb
> [#slice] Get a slice of config options as a hash set

- .gitignore
- CHANGELOG.md
- README.md
- lib/qonfig.rb
- lib/qonfig/data_set.rb
- lib/qonfig/exceptions.rb
- lib/qonfig/loaders.rb
- lib/qonfig/loaders/basic.rb
- lib/qonfig/settings.rb
- lib/qonfig/uploaders.rb
- lib/qonfig/uploaders/base.rb
- lib/qonfig/uploaders/file.rb
- lib/qonfig/uploaders/json.rb
- lib/qonfig/uploaders/yaml.rb
- qonfig.gemspec
- spec/features/clear_options_spec.rb
- spec/features/config_definition_and_representation_spec.rb
- spec/features/expose_yaml_spec.rb
- spec/features/load_from_json_spec.rb
- spec/features/load_from_yaml_spec.rb
- spec/features/save_to_file/save_to_json_spec.rb
- spec/features/save_to_file/save_to_yaml_spec.rb
- spec/spec_helper.rb
- spec/support/spec_support.rb
> [uploaders] File uploaders: JSON, YAML

- qonfig.gemspec
> [gem] updated deps

- .rubocop.yml
- .travis.yml
- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/settings.rb
- spec/features/subset_functionality_spec.rb
> [#subset] An ability to get a subset of config options

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/settings.rb
- spec/features/has_a_key_spec.rb
- spec/features/validation_spec.rb
> [#key?/#setting?/#option?] Setting's key existence checkers

- .rubocop.yml
- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/validator/basic.rb
- lib/qonfig/validator/builder.rb
- lib/qonfig/validator/builder/attribute_consistency.rb
- lib/qonfig/validator/dsl.rb
- lib/qonfig/validator/method_based.rb
- lib/qonfig/validator/predefined/common.rb
- lib/qonfig/validator/predefined/registry.rb
- lib/qonfig/validator/predefined/registry_control_mixin.rb
- lib/qonfig/validator/proc_based.rb
- spec/features/reload_spec.rb
- spec/features/validation_spec.rb
See #74 (Closes #74) 
See CHANGELOG.md
See README.md
See specs :)
> [validations] Strict behaviour

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/settings.rb
- lib/qonfig/version.rb
- see `CHANGELOG.md`/`Fixed` section
> [fix] Incorrect #keys behavior

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/errors.rb
- spec/features/validation_spec.rb
- see `CHANGELOG.md`
- see `README.md`
> [valid_with?] validate potential configurations without any assignment

- CHANGELOG.md
- README.md
- lib/qonfig/data_set.rb
- lib/qonfig/imports/export.rb
- lib/qonfig/imports/general.rb
- spec/features/export_settings_spec.rb
See `CHANGELOG.md`
See `lib/qonfig/dataset.rb`
See `lib/qonfig/imports/general.rb`
See specs :)
> [fix] incorrect default attributes for #export_settings/.import_settings

- CHANGELOG.md
- README.md
- lib/qonfig/dsl.rb
- spec/features/expose_self/format_option_dynamic_spec.rb
- spec/features/load_from_self/with_hash_like_data_representation_spec.rb
- subject :)
- see `README.md`
- see `CHANGELOG.md`
> [DSL/expose-self/load_from_self] format: :dynamic by default

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/qonfig/loaders/json.rb
- lib/qonfig/version.rb
- spec/features/load_from_json_spec.rb
- spec/fixtures/json_with_erb.json
Just added ERB support, like for YAML but for JSON
> ERB support for JSON files
